### ISSUE TITLE
Make the directory structure more flexible

### ISSUE THREAD

**Issue by fabpot** [sensiolabs/SensioDistributionBundle#117]
This bundle assumes that your project follows the default Symfony Standard Edition directory structure (which I think is a good thing). But now that we will probably have a new directory structure (see symfony/symfony-standard#584), we should support both the old and the new way.

So, I propose to add the whole directory structure in the composer variables. Some PRs about a sub-set of this: #5, #10, #74, #83, and #96.

**Comment by gnutix** [comment]
This issue is still not resolved : https://github.com/sensiolabs/SensioDistributionBundle/issues/96
