### ISSUE TITLE
Conflict with symfony 2.5 directory structure

### ISSUE THREAD

**Issue by jumale** [sensiolabs/SensioDistributionBundle#142]
I've tried to configure an app using /config.php in sf2.5 with the new directory structure, and there was an error here https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Configurator/Configurator.php#L188 
it has tried to access the `app/cache` directory instead of the `var/cache`

**Comment by stof** [comment]
The whole way of defining the cache and log folders for the 3.0 directory structure is flawed. Editing the code of the Kernel class when copying it to bootstrap.php.cache means that the 2.5 locations will be used if the bootstrap.php.cache file is not loaded (by people disabling it automatically when [debugging with XDebug](https://gist.github.com/johnkary/601b4071a4b923b22ac2) to make breakpoint working, or when using the Behat Symfony2Extension which does not load the bootstrap file)

**Comment by Tobion** [comment]
Can be closed for the same reason as in #189
