### ISSUE TITLE
Revert "[DistributionBundle] Fix real vendor dir , reading from composer.json"

### ISSUE THREAD

**Issue by gjuric** [sensiolabs/SensioDistributionBundle#186]
I propose that the commit https://github.com/sensiolabs/SensioDistributionBundle/commit/798ddcd26ce04bcf3e0b08dd466ee89c415832ea gets reverted for the reasons I stated in the inline comments (sorry if this complicates issue reporting).

**Comment by fabpot** [comment]
reverted for now.
