### ISSUE TITLE
Backport "Fix composer update via HHVM"  in 2.3.X branch

### ISSUE THREAD

**Issue by allan-simon** [sensiolabs/SensioDistributionBundle#188]
Can this PR  #150  be backported in branch 2.3.X so that we can use it with HHVM , thank you

**Comment by csiewert** [comment]
An answer would be nice...I've the same issues...

**Comment by Kevlys** [comment]
:+1:

**Comment by wojtas** [comment]
See this solution - https://github.com/sensiolabs/SensioDistributionBundle/pull/150#issuecomment-57270246

It helped me. The problem no longer occurs.

**Comment by fabpot** [comment]
Closing as 3.0 is now compatible with 2.3.
