### ISSUE TITLE
Conflict with Symfony 3 structure and Sf 2.5

### ISSUE THREAD

**Issue by sandermarechal** [sensiolabs/SensioDistributionBundle#189]
There is a conflict with Sf 2.5 when using the new Sf3 directory structure. The problem seems to be caused by line 376 in ScriptHandler.php:

```php
$cacheDir = $fs->makePathRelative($bootstrapDir, $autoloadDir);
```

This code generates a path like "../var", which in turn leads to Symfony bug symfony/symfony#12893

**Comment by xabbuh** [comment]
Looks like this is related to #142.

**Comment by Tobion** [comment]
This can be closed as the fragile code has been removed in #242 and the symfony 3.0 overwrites the cache and log dirs in the Kernel manually which doesn't have this problem.
