### ISSUE TITLE
Invalid driver exception when pdo_mysql is not installed

### ISSUE THREAD

**Issue by cbrunnkvist** [sensiolabs/SensioDistributionBundle#191]
When I initialize a new app based on the Symfony standard distribution, the default development app tells me it can "Configure" itself by means of a green large friendly button. I select PostgreSQL in the following form, since that is what my deploy environment is using. 

__Expected__
The configurator wizard should finish and provide me with a valid config...

__Observed__
The first step always ends in an error claiming the PDO driver could not be found - even though _pdo_pgsql_ is available.

__Possible cause__
It seems as if the form validation step causes Doctrine to initialize some object using default values from the initial parameters.yml which is root:""@pdo_mysql, and pdo_mysql is not installed on all systems.

**Comment by fabpot** [comment]
Closing as the configurator has now been removed from the bundle.
