### ISSUE TITLE
Error after update v3.0.18 

### ISSUE THREAD

**Issue by AntonioMalatesta** [sensiolabs/SensioDistributionBundle#196]
After run composer update in my symfony project, I got this error: 

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception.

Error: Call to protected Doctrine\ORM\EntityManager::__construct() from context 'appDevDebugProjectContainer'

What could cause the error? Thanks.

**Comment by xabbuh** [comment]
@AntonioMalatesta Did you configure a service that uses `Doctrine\ORM\Entity` as the `class` value?

**Comment by AntonioMalatesta** [comment]
Sorry my error. 
Yesterday the SensioBundle was update to version 3.0.18 but my symfony version remained outdated. 
I update symfony to version 2.6.4 and all work well. 
Thank you.
