### ISSUE TITLE
intl.error_level must be 0

### ISSUE THREAD

**Issue by dosten** [sensiolabs/SensioDistributionBundle#204]
As seen in symfony/symfony#14430, if the intl.error_level option is set to a value other than 0, the Intl extension will return a warning or an error. Maybe we can add this as a requirement or a recommendation in the SymfonyRequirements.php file. What do you think?

**Comment by fabpot** [comment]
Recommendation looks like better to me.

**Comment by fabpot** [comment]
@dosten Can you make a PR?

**Comment by dosten** [comment]
@fabpot sure

**Comment by fabpot** [comment]
@dosten Would you have time to make the PR?

**Comment by dosten** [comment]
Done, see #209
