### ISSUE TITLE
symfony 2.7 deprecated syntax in installRequirementsFile()

### ISSUE THREAD

**Issue by xaben** [sensiolabs/SensioDistributionBundle#205]
https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php#L210
uses a deprecated syntax for chmod-ing the dumped file. Which in turn for symfony 2.7 throws an exception during composer update:

[ErrorException]
Support for modifying file permissions is deprecated since version 2.3.12 and will be removed in 3.0.

**Comment by fabpot** [comment]
Can you submit a pull request to fix that?
