### ISSUE TITLE
Deprecated error on using Yaml:parse with filename

### ISSUE THREAD

**Issue by shivas** [sensiolabs/SensioDistributionBundle#211]
PHP Deprecated:  The ability to pass file names to the Symfony\Component\Yaml\Yaml::parse method is deprecated since version 2.2 and will be removed in 3.0. Pass the YAML contents of the file instead.

**Comment by shivas** [comment]
Its Configurator class line 165

**Comment by stof** [comment]
Can you send a PR updating this ?

**Comment by xabbuh** [comment]
see #208
