### ISSUE TITLE
can't read parameters.yml on version 2.3.21

### ISSUE THREAD

**Issue by WickedSilver** [sensiolabs/SensioDistributionBundle#213]
I get the following error while trying to update using composer or trying to clear cache:

```
PHP Warning:  file_get_contents(ROOT/apps/app_name/config/parameters.yml): failed to open stream: No such file or directory in /ROOT/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Configurator/Configurator.php on line 165
```

Whenever i change back to version 2.3.20 it works again.
Our parameters.yml is located at ROOT/apps/config/parameters.yml

**Comment by fabpot** [comment]
It has been fixed, but I forgot to release a new version. Done now.
