### ISSUE TITLE
Update composer.json when Symfony Standard files are removed

### ISSUE THREAD

**Issue by xabbuh** [sensiolabs/SensioDistributionBundle#215]
There is a `removeSymfonyStandardFiles()` method in the `ScriptHandler` class that removes some files specific to the Symfony Standard Edition. Unfortunately, the removed files are still referenced in the project's `composer.json` file after the that:

```json
{
    "scripts": {
        "post-root-package-install": [
            "SymfonyStandard\\Composer::hookRootPackageInstall"
        ]
    }
}
```

**Comment by fabpot** [comment]
What about removing this "feature" altogether. It was there to be able to create a Symfony project with the new directory structure, but then the option was remove later on. I propose to remove all the code related to the new directory structure.

**Comment by stof** [comment]
@fabpot I agree. this code converting project structures is broken regarding the way it changes the cache and log dirs (they are still in the 2.x location if you don't load the bootstrap.php.cache file)

**Comment by Tobion** [comment]
This can be closed as it has been removed in https://github.com/symfony/symfony-standard/pull/851
