### ISSUE TITLE
[Suggestion] Move the build.sh and build_demo.sh files to the symfony-installer repo

### ISSUE THREAD

**Issue by stof** [sensiolabs/SensioDistributionBundle#223]
These scripts are used to build the archives needed by the installer. Having them in SensioDistributionBundle, which is installed in projects, does not really make sense.

**Comment by stof** [comment]
Note that these 2 files should of course not be included in the symfony-installer phar.

**Comment by stof** [comment]
@javiereguiluz what do you think about this ?

**Comment by xabbuh** [comment]
I think that's a good idea (well, as long as moving files does not break the process of building the archives on the build server).

**Comment by javiereguiluz** [comment]
@stof I agree that it's the right thing to do. However, as guessed by @xabbuh, this is definitely going to break a lot of things unless we are very careful and plan the move in detail. I'm going to ask our devops guys, which use this file, specially for the `build_demo.sh` file. Thanks.

**Comment by fabpot** [comment]
I'm the one who is using those files, so I'm the only one to be able to move them :)

**Comment by HeahDude** [comment]
@fabpot what's the status of this issue?

**Comment by HeahDude** [comment]
Closing here, see #298.
