### ISSUE TITLE
[feature request] composer scripts for doctrine schema creation

### ISSUE THREAD

**Issue by Ma27** [sensiolabs/SensioDistributionBundle#232]
hey there,

I'm a big fan of that script handler, but I'm currently missing a feature. I would like to be able to create the doctrine schema during the composer install. I would open a PR for that, but I'd like to talk with you about that feature, in order to figure out whether that's useful or not.

**Comment by Ma27** [comment]
ping @fabpot

**Comment by Wirone** [comment]
This out of the scope of SensioDistributionBundle. You can create simple PHP class and register its method as a handler for Composer's `postInstall`, Just [read some documentation](https://getcomposer.org/doc/articles/scripts.md).

This is not something which should be distributable for all users, this is custom behaviour.

**Comment by Ma27** [comment]
I'm aware of that comcenpt. I just had to reimplement that very often, so I wanted to ask whether this kind of new feature can be useful in that bundle.
If not, then it's also fine :)
