### ISSUE TITLE
Confusing symfony-bin-dir parameter

### ISSUE THREAD

**Issue by Wirone** [sensiolabs/SensioDistributionBundle#235]
Recently we wanted to move to new directory structure in our app and I found `symfony-bin-dir` little confusing.

In our apps we almost always have custom binaries, stored in `bin` (and handled with CVS) so in order to not mix it with vendor's binaries and for simpler ignoring these in CVS, we configure Composer to install those files to `bin/vendor` directory (easily excluded by `bin/vendor/*`).

We wanted to move `console` binary into `bin`, but when `symfony-bin-dir` is configured as `bin`, also `security-checker` and `symfony_requirements` files are dumped there. Since we don't want external binaries next to our binaries, we tried to configure `symfony-bin-dir` as `bin/vendor` but then Composer's `postInstall` and `postUpdate` hooks does not work:

    > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
    Could not open input file: bin/vendor/console
    Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

We don't want to move `console` binary to `bin/vendor` because of CLI usage and of course it has to be versioned in CVS.

For now, we ignore `bin/security-checker` and `bin/symfony_requirements` in CVS, but what if Symfony will install another binaries? This is not good if we need to remember to not commit those files, but add them to ignore file.

Or maybe this is wrong approach and those files should be commited?

**Comment by Tobion** [comment]
Symfony 3.0 doesn't use `"config": { "bin-dir": "bin"}` anymore. So vendor bins and project bins are not mixed anymore. `bin/symfony_requirements` should currently be added to the CVS because the idea was to be able to run it without vendors being installed. I tried to improve this with #97. But for now it's not a big deal.

So this issue can be closed.

**Comment by Wirone** [comment]
Ok, thanks for the answer. Just to be clear: Symfony 3.0 uses `symfony-bin-dir` for determining `console` binary and for installing/using `security-checker` and `symfony_requirements`, so is distinguished from `bin-dir` used by Composer?

**Comment by Tobion** [comment]
symfony-bin-dir is only used for console and symfony_requirements (the files that are also in https://github.com/symfony/symfony-standard/tree/master/bin)

**Comment by stof** [comment]
``security-checker`` is just a normal composer bin, so it will depend on your composer ``bin-dir`` config (but be aware that changing this setting will leave the existing bins in place, until you delete them manually)

**Comment by Wirone** [comment]
@stof Ah right. I know about manually deleting/moving - I think I've overlooked `security-checker` in some way so it was my mistake. Now it seems clear. Thanks!
