### ISSUE TITLE
revert execute php process with --php-ini option

### ISSUE THREAD

**Issue by glensc** [sensiolabs/SensioDistributionBundle#236]
please revert #176 or explain the reasoning!

see comments below: https://github.com/sensiolabs/SensioDistributionBundle/pull/176#issuecomment-75266039

**Comment by fabpot** [comment]
The reasoning was that if you pass a specific `php.ini` when running the script, it would also use it for internal PHP calls.

**Comment by HeahDude** [comment]
Closing for above comment.
