### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by mnapoli** [sensiolabs/SensioDistributionBundle#237]
Hi, I cannot find a changelog for new versions, either in the repo or in the tags in the repository. Is it available somewhere? I'm considering updating from v3 to v4 but I'm afraid of any BC breaks.

**Comment by stof** [comment]
The only difference between 3.0x and 4.x is the removal of the AcmeDemoBundle skeleton and of the composer hook allowing to install it (which is why it is a major version)

**Comment by mnapoli** [comment]
OK thank you. I don't know if this issue needs to stay open if you plan to add such changelog somewhere. Else feel free to close it :)

**Comment by stof** [comment]
I cannot close it. I'm not a maintainer on this bundle
