### ISSUE TITLE
Webconfigurator.xml not found

### ISSUE THREAD

**Issue by AlmogBaku** [sensiolabs/SensioDistributionBundle#238]
after upgrading from symfony 2.7 to 2.8 (and all the standard dist deps):

```
FileLoaderLoadException in FileLoader.php line 130:
Unable to find file "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml" in @SensioDistributionBundle/Resources/config/routing/webconfigurator.xml (which is being imported from "/Users/AlmogBaku/Documents/Projects/Rimoto/core/app/config/routing_dev.yml"). Make sure the "SensioDistributionBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml" is not empty.
```

**Comment by AlmogBaku** [comment]
this should be removed from router on tag

**Comment by stof** [comment]
well, either remove this line from your routing file, or don't bump to the new major version of the bundle

**Comment by Siempie93** [comment]
I have the same problem! I don't understand what you mean by 'should be removed from router on tag'

**Comment by stof** [comment]
@Siempie93 remove the import of the file from your config_dev.yml (the web configurator does not exist anymore since the 4.0 release of the bundle)

**Comment by Siempie93** [comment]
@stof Ooh OK, I see. Thanks a lot!

**Comment by sevenup30** [comment]
Hi, 
I just updated to symfony 2.8 and got this issue, But i dont have any import into my config_dev.yml or other config.yml,
how should I fix it?

**Comment by xabbuh** [comment]
@sevenup30 It's probably loaded in `routing.yml` or `routing_dev.yml`. Otherwise, please post the exact error message you get.

**Comment by lechaabani** [comment]
I got the same issue, so i remove this routing from the file ```routing_dev.yml```
```
_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator
```
It work now

**Comment by sevenup30** [comment]
@xabbuh 
Thanks I remove the _configurator block and it now works. I missed it before because there is no link with fosjs.

@lechaabani 
Yeah it was the block to remove ! Thank
