### ISSUE TITLE
Need Symfony 3.0-compatible release

### ISSUE THREAD

**Issue by weaverryan** [sensiolabs/SensioDistributionBundle#240]
The 3.0 support was merged into `master` only: sha: 30f175de52cbf509d542eb09f0501084665e21a5

And there's no release for this yet. Could we backport this change to the 4.0 branch and make another tag? Or is the master branch ready for a 5.0 tag?

Thanks!

**Comment by fabpot** [comment]
I was about to release 5.0 but I wanted to remove support for the flag that makes it possible to switch to the Symfony 3 dir structure, but I think I won't have time, too bad.

**Comment by weaverryan** [comment]
Yes, I see #226. That is a shame. If 4.0 is really compatible with Symfony 3.0, we could add compat there, tag a new 4.0, then tag 5.0 later when we have a bit more time.

**Comment by fabpot** [comment]
Doing the backport would be an even bigger work. I think I'm just going to release as is.

**Comment by fabpot** [comment]
Done, I've just removed the documentation of the flag from the README. We should probably do the same from the Symfony docs if it's documented.

**Comment by weaverryan** [comment]
Thanks - I just checked the docs and there's nothing mentioned there - I think we're good.

**Comment by xabbuh** [comment]
@fabpot It's not documented yet. So we are fine here.
