### ISSUE TITLE
clearCache error with 5.0.1 on Symfony 2.7.7 project

### ISSUE THREAD

**Issue by Vrtak-CZ** [sensiolabs/SensioDistributionBundle#243]
```
muse:project:% composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing sensio/distribution-bundle (v4.0.3)
  - Installing sensio/distribution-bundle (v5.0.1)
    Loading from cache

Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Class 'Symfony\Component\Console\Input\ArgvInput' not found in /Users/vrtak-cz/Workspace/project/app/console on line 17
PHP Stack trace:
PHP   1. {main}() /Users/vrtak-cz/Workspace/project/app/console:0

Fatal error: Class 'Symfony\Component\Console\Input\ArgvInput' not found in /Users/vrtak-cz/Workspace/project/app/console on line 17

Call Stack:
    0.0003     232144   1. {main}() /Users/vrtak-cz/Workspace/project/app/console:0

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception



  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command.



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--] [<packages>]...
```

**Comment by Vrtak-CZ** [comment]
"workaround": add `require_once __DIR__.'/../vendor/autoload.php';` after `require_once __DIR__.'/bootstrap.php.cache';` in `app/console`

**Comment by tubssp** [comment]
i have the same problem here

**Comment by canou** [comment]
Maybe you should check if all your files are in sync, in particular with changes made about https://github.com/sensiolabs/SensioDistributionBundle/pull/242

I think about files which aren't updated when doing `composer update`, ie the console file itself, plus maybe some others.

Got the same problem with a Symfony 2.8 project, turns out I was missing changes in console file (and app.php, app_dev.php, composer.json too, but it may not be useful regarding this particular issue).
I took example on https://github.com/symfony/symfony-standard to reflect changes made to this file, and now it's fixed.

**Comment by stof** [comment]
sensio/distribution-bundle 5 indeed requires some changes in the files of the main project, as we changed the way we handle the autoloader registration.
If you upgrade to the new major version of the bundle, you need to make these changes in your project. Otherwise, stay on 4.x

**Comment by Vrtak-CZ** [comment]
@canou & @stof thank you. If I use `app.php`, `app_dev.php` and `app/console` from Symfony Standard Edition 2.8 it works ok. But should be somewhere "upgrade guide" or `MIGRATION.md` or something like that.

**Comment by Tobion** [comment]
See https://github.com/symfony/symfony-standard/pull/890

@fabpot maybe it would be a good idea to copy the distribution-bundle related changes from my SE PR to this repo. Or just add a link to the SE upgrade file here somewhere (in the github release tag?)

**Comment by apfelbox** [comment]
@Tobion I agree, this bundle should have an UPGRADE file.

**Comment by hhamon** [comment]
Was able to replicate the problem. I had to downgrade to version 3.0.12 to make my application work.

The diff between my old ` app/bootstrap.php.cache` and the new one is the following:

```diff
> namespace {
>     error_reporting(error_reporting() & ~E_USER_DEPRECATED);
>     $loader = require_once __DIR__.'/./autoload.php';
> }
>
3308a3314,3315
>
> namespace { return $loader; }
```
It seems the namespace bloc at the top as an invalid generated path.

**Comment by Tobion** [comment]
@hhamon No sure what you need to replicate here. The necessary upgrade is already documented: https://github.com/symfony/symfony-standard/blob/2.8/UPGRADE-2.8.md

**Comment by hhamon** [comment]
Thanks @Tobion I'm gonna check it out and let you know!

**Comment by Jean85** [comment]
Should this mean that 4.x of this bundle is for SF <2.8?

**Comment by Tobion** [comment]
No this bundle works with any symfony version as you can see in composer.json. The changes here only affect the standard-edition.

**Comment by rparsi** [comment]
@Tobion I have the exact same issue while trying to upgrade my 2.7 Symfony project to 2.8.
I applied the updates as described in https://github.com/symfony/symfony-standard/blob/2.8/UPGRADE-2.8.md, but am still getting the error

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

when running composer install or update

I tried creating a new empty Symfony 2.8 project and copying the app, app_dev, console files over.
I get same error with following detail

Fatal error: Class 'AppKernel' not found in /home/rahi/src/api/app/console

I also tried copying app/console from upstream Symfony 2.8, getting same error.

I may be missing something stupid, any ideas?
My fallback is to migrate current project into new one, but that would be a lot of work as I have entities with Sonata admin bundle integration.

**Comment by Tobion** [comment]
> The app/AppKernel.php and app/AppCache.php files are now autoloaded via Composer.

See https://github.com/symfony/symfony-standard/blob/2.8/composer.json#L8

**Comment by rparsi** [comment]
@Tobion That was it, the one thing I forgot to verify in my composer.json was the autoload value.  Thanks for the help, much appreciated.

**Comment by sherif807** [comment]
hi I just updated to symfony 2.8, but my application failed when I updated distributionBundle to 5.0, I am trying to fix it but I don't understand how to do these instructions 

The generated app/bootstrap.php.cache does not include autoloading anymore. So you need to add the autoloading code in your front controllers web/app.php, web/app_dev.php, app/console and app/phpunit.xml.dist (bootstrap config).
If you have been using the Symfony 3 directory structure already, you need to overwrite the cache and log directories in your AppKernel as it is also done in Symfony 3 now (see app/AppKernel.php).

would someone kindly explain how can I do this?
