### ISSUE TITLE
Could not open input file: app/console

### ISSUE THREAD

**Issue by jpyzio** [sensiolabs/SensioDistributionBundle#245]
After "git clone" project (Symfony 3) and type "composer install".

```
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
[...]
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Creating the "app/config/parameters.yml" file
Some parameters are missing. Please provide them.
database_driver (pdo_sqlite): 
[...]
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Could not open input file: app/console
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:  
  Could not open input file: app/console                                     
  .                                                                          
                                                                             
install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [packages1] ... [packagesN]
```
Because in: vendor/sensio/distribution-bundle/Composer/ScriptHandler.php:464 function "is_dir($options['symfony-var-dir'])" returns false, because when  method "clearCache" is executed, directory "var" in project is not created yet and composer try execute app/console instead bin/console

EDIT:
The problem is in symfony .gitignore file. It adds all the subdirectories with the "var" to ignore. After cloning the repository above method can not work properly.

**Comment by stof** [comment]
symfony-standard has .gitkeep files ensuring that the folder exists. If your own project does not keep the folders, it might indeed break

**Comment by jpyzio** [comment]
I know about it, but this problem is not only in my project.
Here is explanation of problem: https://github.com/symfony/symfony/issues/16815

**Comment by xabbuh** [comment]
see symfony/symfony-installer#211

**Comment by jpyzio** [comment]
Thank you, I already solved this problem. When I install new project (installer v1.4.1), it makes old version of .gitignore, but after update (installer v1.4.4) - all is ok.
