### ISSUE TITLE
`useNewDirectoryStructure` does not work with default SF3 setup

### ISSUE THREAD

**Issue by danielsreichenbach** [sensiolabs/SensioDistributionBundle#248]
Given you're installing Symphony 3.0 and putting it into Git, this will most likely fail. `useNewDirectoryStructure` checks if the `var` directory exists but it is excluded from being added to git in the default SF3 project templates git ignore list.

Effectively this renders cache clearing broken because it never will resolve to the new SF 3.0 directory structure in cases where you use git.

**Comment by HeahDude** [comment]
It seems this issue is not related to this bundle. Feel free to reopen if you encounter this issue again.
