### ISSUE TITLE
 Webconfigurator.xml not found

### ISSUE THREAD

**Issue by Siempie93** [sensiolabs/SensioDistributionBundle#257]
I have the same problem as this one  [Webconfigurator.xml not found #238 ](https://github.com/sensiolabs/SensioDistributionBundle/issues/238)

But I don't understand what to do. Can someone please help me?

**Comment by stof** [comment]
Remove the import of this file, as the webconfigurator is gone

**Comment by Siempie93** [comment]
Ok, so where do I have to go to remove the import?

**Comment by Siempie93** [comment]
@stof Nevermind. I see you have also commented on the original issue. Thanks

**Comment by Siempie93** [comment]
@stof I assume I have to remove this lines:
`assetic:
    use_controller: "%use_assetic_controller%"`

Because I don't see any other differences from [this](https://github.com/symfony/symfony-standard/blob/2.8/app/config/config_dev.yml) fil

**Comment by stof** [comment]
@Siempie93 this is totally unrelated. It depends whether you use AsseticBundle or no, which has nothing to do with SensioDistributionBundle (it is not there anymore in the standard edition because AsseticBundle is not included in it anymore)

**Comment by Siempie93** [comment]
I understand that it is not there anymore because of that bundle that's not included anymore. But what is the import of the webconfigurator in the config_dev.yml file then?

**Comment by Siempie93** [comment]
Don't you mean inside the routing_dev.yml file?
This:
`_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator`
