### ISSUE TITLE
Deprectation Notices

### ISSUE THREAD

**Issue by csiewert** [sensiolabs/SensioDistributionBundle#269]
Hey, I noticed some deprecation notices when running composer update in my symfony2 application.

Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap declared at /var/www/foo/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php accepts a Composer\Script\CommandEvent but post-update-cmd events use a
Composer\Script\Event instance. 
Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:289

Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache declared at /var/www/foo/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php accepts a Composer\Script\CommandEvent but post-update-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:289

Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets declared at /var/www/foo/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php accepts a Composer\Script\CommandEvent but post-update-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:289

Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile declared at /var/www/foo/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php accepts a Composer\Script\CommandEvent but post-update-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes
in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:289

Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget declared at /var/www/foo/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php accepts a Composer\Script\CommandEvent but post-update-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes
in phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:289^

Is there something broken?

I'm using symfony 2.8 and sensio/distribution-bundle 2.3

Best
Christian

**Comment by stof** [comment]
sensio/distribution-bundle 2.3 is totally outdated. The current stable release is 5.0.6

**Comment by csiewert** [comment]
Ok, I updated to ~5.0 and notices are gone now. Thank you.

**Comment by Glideh** [comment]
Well with a SF2 installation I guess everything is outdated now.
Shouldn't we still be able to do composer installs or updates ?

**Comment by stof** [comment]
@Glideh the fact that composer displays a deprecation notice does not prevent `composer install` from running.

**Comment by Glideh** [comment]
Ho sorry that's right, I was mixing with another issue.
I going to remove my comments.
