### ISSUE TITLE
Give more freedom to directories

### ISSUE THREAD

**Issue by AmsTaFFix** [sensiolabs/SensioDistributionBundle#270]
in ```AppKernel``` everyone can change path to ```logs```/```cache``` dir, but in bundle we can only use ```var```/```app``` dir, why? In my situation I:
* don't have ```app``` dir, but have ```app_```, because have legacy ```App``` directory with classes
* can't change ```cache``` directory to ```var/cache```, because have problems with directory permissions. 
* don't use ```web``` directory to save static files, we have subdomain to access them... 

Symfony is very flexible, but distribution bundle not... Can we solve this? Or only i and my project have problems like these? We can add dirs like:
* ```assets_dir```
* ```cache_dir```

**Comment by stof** [comment]
The bundle supports the new directory structure if you use an uptodate version of the bundle. 3.x versions of symfony-standard are configuring the bundle to use the new system btw.

**Comment by AmsTaFFix** [comment]
but if we don't use "canonical" structure of SF2/SF3? We transfer our project on SF3 Kernel and have some dirs in old places

**Comment by stof** [comment]
@AmsTaFFix there is nothing hardcoding the SF3 structure in this bundle. There is only a bunch of necessary configuration settings to allow symfony-standard to use the new structure (we had to add a new configuration setting which was not necessary for SF2). You can use them to configure things for your own case.

**Comment by AmsTaFFix** [comment]
@stof i'm sorry, i inspect the code and test how it works in my project, last question about assets directory? Can we have optional option for assets directory? like in ```assets:install``` command?

**Comment by HeahDude** [comment]
Hi @AmsTaFFix actually this bundle use the [`composer.json` settings](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php#L51-L54), isn't it enough to support your use case?

**Comment by HeahDude** [comment]
`assets:install` use the directory marked as `symfony-web-dir` in the extra config of the `composer.json`.

Feel free to reopen if you miss a feature to discuss this further.
