### ISSUE TITLE
best version for Symfony2.8

### ISSUE THREAD

**Issue by kimwue** [sensiolabs/SensioDistributionBundle#273]
How can I find out what's the suited version to a Symfony version?

Thx,
Kim

**Comment by HeahDude** [comment]
You can safely go for the latest release 5.0 from symfony 2.3+ et 3.0 and php 5.3+. If you use earlier version of symfony looking at the `composer.json` for a given tag will help :)

**Comment by kimwue** [comment]
Awesome! Thanks.
