### ISSUE TITLE
[SymfonyRequirements] No way to avoid the ICU recommendation warning?

### ISSUE THREAD

**Issue by andrerom** [sensiolabs/SensioDistributionBundle#277]
_This issue is potentially beyond just SensioDistributionBundle, what follows below is the symptom:_

In 5.x a few new recommendations where added in regards to ICU version: https://github.com/sensiolabs/SensioDistributionBundle/compare/v4.0.7...v5.0.8#diff-e6f244c4652860546283a91a210dc2f4R682

However when building PHP on for instance Debian Jessie _(default for docker library containers)_, you'll have version 52.x, and as of how Intl works now there does not seem to be a sensible way to make sure you pass all recommendations anymore. And to make matters worse it's a moving target, even for backports.

---

It seems somewhat wrong to imply we should uninstall Intl extension. And btw that I'm not saying things where better in  < 2.6 where you would typically have lock files pointing to on Intl/Icu version while person installing might be using something completely different ;)

Maybe Symfony needs to come bundled with several versions? Or the recommendation here needs to be less strict?

/cc @jakzal @webmozart

**Comment by jakzal** [comment]
Problem is that the only valid ICU version is the latest one. I think it's fine to ignore those recommendations that are not relevant to your app.

See #274

**Comment by andrerom** [comment]
> I think it's fine to ignore those recommendations that are not relevant to your app.

This is build testing, and afaik no reliable way to ignore one recommendation, so this forces it to not check recommendations at all.

> Problem is that the only valid ICU version is the latest one.

The whole logic here implies you'll in worst case have to chase unofficial packages for icu, or compile yourself, and not just the most recent one, but the exact one Symfony uses, _on every single composer update containing Symfoy updates._

Which makes me question the overall logic here, as it seems strange to couple Symfony code base so tightly with a specific icu versions of the system. Given that we know different distros are on different versions, and most don't have all possible versions available.

/cc @fabpot

**Comment by HeahDude** [comment]
Maybe we you should only change the icu version on symfony master?

**Comment by andrerom** [comment]
That will avoid it being a moving target for most, however for those able to upgrade to latest, which indeed would be recommended, it will then not be a good solution.


Maybe rather an option to filter out/in specific recommendations either by type or by severity.

Or I'll just have to adjust and only display recommendations and not fail the build by them because of this one.

**Comment by fabpot** [comment]
We should probably make it like something people might want to do but without failing the check.

**Comment by andrerom** [comment]
One thing I haven't fully got here as I'm not so deep into how Intl Component works:

Is there any correlation at all between the built in ICU fallback and the one provided by the system if `intl` extension is enabled? As in any part of the system that either loads both for some reason, or expect a very very specific behavior from the icu layer?

1.a. If yes, should Symfony bundle several versions? Could that be done in a better way than what was done in earlier symfony versions that led us to this?
1.b. If just tests suites, should maybe not the requirements of the tests suites, aka require-dev, spill over to recommendations for user land? Maybe recommendations could rather be a somewhat recent version, 51.x and up or something?
2. If not, then why the strictly correlating recommendation? see 1b

**Comment by jakzal** [comment]
> Is there any correlation at all between the built in ICU fallback and the one provided by the system if intl extension is enabled?

The built in ICU fallback is generated based on a certain version of the ICU library (preferably the latest). The intl extension is also built based on a certain version of the ICU library. 

Most of stubs from the component won't be used if there's intl extension present. However, since the  intl extension doesn't expose everything, the Symfony component does provide some additional data. So even if you have the intl extension installed you might be using some of the component's features. This is why it's recommended to have the component version match the extension version. Otherwise you might run into some inconsistencies. 

Furthermore it's recommended to always use the latest intl extension version to get data that's up to date.

> should Symfony bundle several versions? 

No. It only makes sense to use the most recent version, as all the previous ones are no longer valid.

**Comment by fabpot** [comment]
Closing this issue as this bundle is now deprecated. Symfony Flex replaces this bundle.
