### ISSUE TITLE
[Bug] v5.0.9 breaks some caching for Classes

### ISSUE THREAD

**Issue by waplet** [sensiolabs/SensioDistributionBundle#282]
Hello, seems like latest version on this bundle breaks something in Symfony
https://github.com/sensiolabs/SensioDistributionBundle/commit/c956be2f4a0984c6bce41e9f81becb69a41cc350

```
PHP Fatal error:  Cannot declare interface Symfony\Component\DependencyInjection\ContainerAwareInterface, because the name is already in use in /tmp/var/prod/cache/classes.php on line 7553
exit code 255
```

**Comment by HeahDude** [comment]
ping @nicolas-grekas

**Comment by nicolas-grekas** [comment]
@waplet which version of symfony do you have? Did you clear the cache completely (i.e. by doing first a `composer install` then a `app/console cache:clear`?

**Comment by waplet** [comment]
@nicolas-grekas We are using Symfony 2.8.10;

I guess that's something behind bootstrap.cache.php and classes.php files, but can't really figure it out.
It happens when 
`include_once __DIR__.'/../var/bootstrap.php.cache';` and `$kernel->loadClassCache();` is enabled;

Cache clearing is made as hook in composer.json

**Comment by waplet** [comment]
Seems like the bug was due to fact, that `implement ContainerAwareInterface` was called before cached class loaded.
And afterwards the cache tried to create new class definition.

**Comment by nicolas-grekas** [comment]
Why did you close? Found an issue on your side?

**Comment by waplet** [comment]
Yes, it was somehow issue with `Commands` which `implemented ContainerAwareInterface;`

**Comment by HeahDude** [comment]
Great! Thanks @waplet for the feedback.
