### ISSUE TITLE
The bundle references removed images from the FrameworkBundle

### ISSUE THREAD

**Issue by xabbuh** [sensiolabs/SensioDistributionBundle#291]
The images removed in https://github.com/symfony/symfony/pull/19996 are still referenced :)

web/config.php
![image](https://cloud.githubusercontent.com/assets/1047696/19022896/691adbde-88e2-11e6-8acc-a60ad97c3583.png)

see symfony/symfony-standard#995

**Comment by HeahDude** [comment]
See #292.
