### ISSUE TITLE
assets dir in ScriptHandler::installAssets

### ISSUE THREAD

**Issue by IndraGunawan** [sensiolabs/SensioDistributionBundle#295]
```php
// Composer/ScriptHandler.php

protected static $options = array(
        // ...
        'symfony-assets-dir' => 'web',
        // ...
    );
```

how about add symfony-assets-dir options to handle custom assets:install target path?
if no symfony-assets-dir set at composer.json it use the symfony-web-dir options.

**Comment by HeahDude** [comment]
I'm -0 for this, assets are statics and should be in the public folder or CDN. What's your use case?

**Comment by IndraGunawan** [comment]
for example i have symfony apps named `example.com` and setup correctly.
then i would like to use another domain to access all my assets. lets say `static.example.com` this domain point to `<project_dir>/web/static` so the asset files must located at `web/static`

because framework bundle configuration support for this.
```yml
framework:
   assets:
        base_urls: "%assets.domain%"
```

this time i remove scriptHandle:installAssets and run assets:install command manually.
but if it can handle by default why not.

i will patch this section if approved.

**Comment by fabpot** [comment]
Closing this issue as this bundle is now deprecated. Symfony Flex replaces this bundle.
