### ISSUE TITLE
Fix php detection when called by composer 1.3+

### ISSUE THREAD

**Issue by Seldaek** [sensiolabs/SensioDistributionBundle#299]
As Composer 1.3RC is out, this should be done to avoid any problems with our new xdebug-circumvention code..

See https://github.com/composer/composer/issues/5783#issuecomment-265133968 and especially the last comment for details. If you want maximum compatibility, you can use `Composer\Composer::VERSION` to do it selectively for new versions, but this is set to a git hash for snapshot builds so maybe rather check if VERSION is not a hash and is below 1.3 then do the old behavior, otherwise do new behavior (as snapshots are more likely to be recent I guess..)

**Comment by gondo** [comment]
this issue was fixed for a while but latest `self-update` caused composer to update to `version 1.3.0 2016-12-24 00:47:03` and the issue re-appeared

**Comment by Pharkie** [comment]
Same as @red-smeg:

`composer update`

using composer 1.3.0 (Symfony 2.8.15, PHP 5.6 on Ubuntu 16.04.01LTS) gives 

`Cannot load Zend OPcache - it was already loaded
PHP Warning: Module 'mysqlnd' already loaded in Unknown on line 0
PHP Warning: Module 'PDO' already loaded in Unknown on line 0`
...and so on for every PHP module, and this appears multiple times each time PHP is invoked. Looks like an issue with composer and using multiple (copies of) the PHP ini file?

This started happening I think when I changed my composer.json to use 

'"sensio/distribution-bundle": "~5.0"'

Hope this can be fixed.

**Comment by kachkaev** [comment]
I just ran `composer update sensio/distribution-bundle` (v5.0.15 => v5.0.17) and the warnings disappeared! Thanks a lot for the fix @fabpot!

**Comment by Pharkie** [comment]
Confirmed fixed this end too: 'composer update' now runs without any PHP module warnings. Huge thanks.

**Comment by tiemevanveen** [comment]
Thanks for backporting this to v4 as well @fabpot!
