### ISSUE TITLE
buggy implementation of `getConsoleDir` if `var/` is not existing

### ISSUE THREAD

**Issue by mweibel** [sensiolabs/SensioDistributionBundle#301]
We just had the case that our deployment failed after upgrading to Symfony3 in the `clearCache` step (composer postinstall). 

The problem was that we didn't upload the `var/` directory to the container and therefore the check in `getConsoleDir -> useNewDirectoryStructure` tries to use `app/console` instead of `bin/console`. 

The implementation of `getConsoleDir` is less than ideal, IMHO. `getConsoleDir` should find a different check in which directory the console is. How about replacing that with this implementation?

```php

    /**
     * Returns a relative path to the directory that contains the `console` command.
     *
     * @param Event  $event      The command event
     * @param string $actionName The name of the action
     *
     * @return string|null The path to the console directory, null if not found.
     */
    protected static function getConsoleDir(Event $event, $actionName)
    {
        $options = static::getOptions($event);
        $binDirExists = static::hasDirectory($event, 'symfony-bin-dir', $options['symfony-bin-dir'], $actionName);
        
        if ($binDirExists && file_exists($binDirExists.DIRECTORY_SEPARATOR.'console')) {
            return $options['symfony-bin-dir'];
        }

        return $options['symfony-app-dir'];
    }
```

Related: #248

**Comment by Tobion** [comment]
👍

**Comment by fabpot** [comment]
Closing this issue as this bundle is now deprecated. Symfony Flex replaces this bundle.
