### ISSUE TITLE
Cannot use '@dev' version

### ISSUE THREAD

**Issue by garak** [sensiolabs/SensioDistributionBundle#309]
I'd like to try the latest version of this bundle, but I don't want to get an ugly "dev-master" in my composer.json. But, since I use `"minimum-stability": "dev"` and `"prefer-stable": true`, I can't get it.
This is caused by the "branch-alias" option in this bundle, that is currently set to a version equal to the stable one (e.g. `5.0.x-dev`), while it should be higher (e.g. `5.1.x-dev`).

**Comment by xabbuh** [comment]
I do not understand your issue. Since there was no `5.1.x` release yet, `5.0.x-dev` should work just fine. Can you please show the version constraint you used and the exact error message you got?

**Comment by garak** [comment]
The purpose of "branch-alias" should be just that: allowing you to select a version that is not yet released, without relying on "dev-master". So, when the new version will be out, you'll just get *that* version (and not, for example, the following one).
I'm not getting any error: simply, with my configuration, requiring "5.0@dev" is installing 5.0.18, not master.

**Comment by xabbuh** [comment]
Well, but that's expected if you set `prefer-stable` to `true`. If you want to have the not released version, you will need to depend on, for example, `^5.0.19`.

**Comment by garak** [comment]
That will not work. First, I should use something like `^5.0.99`, because I want to get the latest updates on master, event after a possible future relase of `5.0.19`, `5.0.20`, etc. Then, I expect that the current master will turn, sooner or later, in `5.1.0` and then I want that stable release

**Comment by xabbuh** [comment]
Afaik the only solution for that is to set `prefer-stable` to `false` then.

**Comment by garak** [comment]
Look, almost every other repository is adapting the strategy I'm suggesting. Just take a look to symfony's composer.json, it's targeting `3.3-dev` as branch-alias (and that version is to be released next May)

**Comment by xabbuh** [comment]
But for Symfony that's only working because existing minor versions have their own branches which is not the case here.

**Comment by garak** [comment]
There's not `3,3` branch (not yet, at least) in Symfony. Anyway, you could also set branch-alias to the next predictable branch, e.g. `6.0` (by the way, event the `5.0` branch is missing, but I see `2.1`-`2.3` branches).
Also, that's not related to actual branches.

**Comment by fabpot** [comment]
The big difference between Symfony and here (same goes for Twig for instance) being that the current master branch is 5.0 and we mean it. There is no 5.1 version of the bundle. We would bump it to 5.1 whenever we will add a new feature. But as long as this is only about bug fixes, there is no reason to bump the version to 5.1.

**Comment by garak** [comment]
It seems to me unlikely that you'll never go with 5.1, being this a Symfony bundle (so, at one point, it will be needed to adapt to Symfony changes, that are likely to happen with major releases).
Anyway, how can I solve my initial issue? Again, the need is to get the latest changes, without relying on "dev-master" and trying to get the stable versions whenever possible.

**Comment by stof** [comment]
well, the dev version of this bundle is currently the dev version of the next 5.0.x release, as there is nothing yet making it a 5.1 one.
So yeah, one day we will bump it to 5.1. but it may be in 2 years only if we don't have any new features to add. Adapting to new versions of Symfony is not a feature.

**Comment by garak** [comment]
I see. So I guess that I'll stick with '^5.0'. Thanks for the clarifications
