### ISSUE TITLE
non well formed numeric value

### ISSUE THREAD

**Issue by Fabr9193** [sensiolabs/SensioDistributionBundle#312]
Hello ! I am having this issue when launching the clearCache script when using composer install :/

    [Symfony\Component\Debug\Exception\ContextErrorException]
    Notice: A non well formed numeric value encountered

even though i have tried to add a php.ini and change my own value
when i type php -i | grep -i "realpath" i get :
realpath_cache_size => 4096k => 4096k

my version is 5.0.18 and i have the "fix" 

https://github.com/sensiolabs/SensioDistributionBundle/commit/68e3dc02e66fec5036557d457cfdffa332a40da4

**Comment by fabpot** [comment]
Closing this issue as this bundle is now deprecated. Symfony Flex replaces this bundle.
