### ISSUE TITLE
ConfiguratorController class extends Symfony\Component\DependencyInjection\ContainerAware that is deprecated since version 2.8, to be removed in 3.0.

### ISSUE THREAD

**Issue by crmpicco** [sensiolabs/SensioDistributionBundle#314]
I was previously using v3 of the DistributionBundle with Symfony 2.7, however as part of a recent upgrade to Symfony 2.8.18 I have upgraded to v4.0.38.

composer.json:
`"sensio/distribution-bundle": "~4.0",`

`  - Updating sensio/distribution-bundle (v3.0.36 => v4.0.38): Downloading (100%)  `

I have had a look around and can see a [similar issue](https://jira.ez.no/browse/EZP-25335) reported on the eZ Publish project, which has a [corresponding PR](https://github.com/ezsystems/ezpublish-kernel/pull/1550/files). However, I am not extending `ContainerAware` and this deprecation notice reports on the `ConfiguratorController`.

Do I need to upgrade further to v5 and will this solve this issue?

```
The Sensio\Bundle\DistributionBundle\Controller\ConfiguratorController class extends Symfony\Component\DependencyInjection\ContainerAware that is deprecated since version 2.8, to be removed in 3.0. Use the ContainerAwareTrait instead.

    DebugClassLoader::loadClass()
    spl_autoload_call()
    class_exists() (called from classes.php at line 2481)
    ControllerNameParser::parse() (called from DelegatingLoader.php at line 100)
    DelegatingLoader::load() (called from classes.php at line 1594)
    Router::getRouteCollection() (called from classes.php at line 1375)
    Router::getMatcherDumperInstance() (called from classes.php at line 1325)
    Router::Symfony\Component\Routing\{closure}()
    call_user_func() (called from ResourceCheckerConfigCacheFactory.php at line 46)
    ResourceCheckerConfigCacheFactory::cache() (called from classes.php at line 1334)
    Router::getMatcher() (called from classes.php at line 1299)
    Router::matchRequest() (called from classes.php at line 2091)
    RouterListener::onKernelRequest()
    call_user_func() (called from WrappedListener.php at line 61)
    WrappedListener::__invoke()
    call_user_func() (called from classes.php at line 1863)
    EventDispatcher::doDispatch() (called from classes.php at line 1778)
    EventDispatcher::dispatch() (called from TraceableEventDispatcher.php at line 140)
    TraceableEventDispatcher::dispatch() (called from bootstrap.php.cache at line 3211)
    HttpKernel::handleRaw() (called from bootstrap.php.cache at line 3181)
    HttpKernel::handle() (called from bootstrap.php.cache at line 3335)
    ContainerAwareHttpKernel::handle() (called from bootstrap.php.cache at line 2540)
    Kernel::handle() (called from app_dev.php at line 28)
```

**Comment by HeahDude** [comment]
Hi @crmpicco, indeed upgrading to v5 will fix this issue as there is no controller anymore.
But this may cause an error (instead of a deprecation notice) if you don't remove the corresponding route in `routing_dev.yml`.
Don't forget to read the [UPGRADE file](https://github.com/sensiolabs/SensioDistributionBundle/blob/master/UPGRADE.md).

**Comment by stof** [comment]
We know ContainerAware is deprecated. But the way to make your project ready for Symfony 3 is already known: migrating to v5.

**Comment by crmpicco** [comment]
Thanks for the confirmation and pointing me in the right direction, @HeahDude . This [diff](https://github.com/symfony/symfony-standard/compare/2.7...2.8#diff-64a0fd926147fcc158821dcb6f1b4d11) also helped greatly.
