### ISSUE TITLE
Multiple Kernels

### ISSUE THREAD

**Issue by Vandersteen** [sensiolabs/SensioDistributionBundle#316]
Hello,

I'm trying to have a Symfony project with multiple kernels, I got most of it working except the composer install part.

So i've moved the app directory in an apps directory and copy'd and edited accordingly each other 'app' (api, ...)

* apps
    * app
        * config
        * autoload.php
        * AppKernel.php
        * ...
    * api
        * config
        * autoload.php
        * ApiKernel.php
        * ...

I had to change some paths in the kernels to find the vendor/autoload and add the parameters `incenteev-parameters` had to check on install.

    "extra": {
        "symfony-app-dir": "apps/app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": [
            {
                "file": "apps/app/config/parameters.yml"
            },
            {
                "file": "apps/api/config/parameters.yml"
            }
        ]
    }

Running `composer install` works without errors with the above. But only the bootstrap.php.cache of `apps/app` get's generated now.

Is there a way to have multiple `symfony-app-dir` or did I copy to much from the default app directory:

* apps
    * autoload.php
    * check.php
    * ...
    * app
        * config
        * AppKernel.php
        * ...
    * api
        * config
        * ApiKernel.php
        * ...

What about the other DistributionBundle scripts (clearCache, installAssets, ...) ?

**Comment by fabpot** [comment]
Closing as this bundle does not support this setup and will never.
