### ISSUE TITLE
composer hangs at Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget

### ISSUE THREAD

**Issue by Bubelbub** [sensiolabs/SensioDistributionBundle#321]
Hey guys,

I have a problem with `Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget`.
Each time I'm using `php composer.phar install` or `php composer.phar update` it hang up on `Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget`.

Is this problem related to this script? Do someone knows this?

Thanks in Advance!

**Log:**

	Reading C:/Users/Bubelbub/AppData/Local/Composer/repo/https---packagist.org/provider-symfony$web-profiler-bundle.json from cache
	Reading C:/Users/Bubelbub/AppData/Local/Composer/repo/https---packagist.org/provider-symfony$web-server-bundle.json from cache
	Reading C:/Users/Bubelbub/AppData/Local/Composer/repo/https---packagist.org/provider-symfony$workflow.json from cache
	Resolving dependencies through SAT
	Dependency resolution completed in 1.078 seconds
	Analyzed 10067 packages to resolve dependencies
	Analyzed 557869 rules to resolve dependencies
	Nothing to install or update
	Resolving dependencies through SAT
	Dependency resolution completed in 0.001 seconds
	Reading C:\xampp\htdocs\vendor/composer/installed.json
	Reading ./composer.lock
	Generating autoload files
	> post-update-cmd: @symfony-scripts
	> symfony-scripts: Incenteev\ParameterHandler\ScriptHandler::buildParameters
	Updating the "app/config/parameters.yml" file
	> symfony-scripts: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
	> symfony-scripts: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

	 // Clearing the cache for the dev environment with debug true

	 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.

	> symfony-scripts: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

	 Trying to install assets as relative symbolic links.

	 -- -------- ----------------
		 Bundle   Method / Error
	 -- -------- ----------------

	 [OK] All assets were successfully installed.

	> symfony-scripts: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
	> symfony-scripts: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget

**Comment by neFAST** [comment]
Same issue here, what's in your composer.json?

**Comment by MartinMa** [comment]
Same issue here. This is my composer.json:

Using composer version 1.5.2.

```json
{
  "name": "bla/blabla",
  "description": "blablabla",
  "type": "project",
  "license": "proprietary",
  "autoload": {
    "psr-4": {
    "AppBundle\\": "src/AppBundle"
  },
  "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
  },
  "require": {
    "php": "^7.1",
    "doctrine/doctrine-bundle": "^1.6",
    "doctrine/orm": "^2.5",
    "ext-intl": "*",
    "ext-mbstring": "*",
    "incenteev/composer-parameter-handler": "^2.0",
    "sensio/distribution-bundle": "^5.0.19",
    "sensio/framework-extra-bundle": "^3.0.2",
    "symfony/monolog-bundle": "^3.1.0",
    "symfony/polyfill-apcu": "^1.0",
    "symfony/swiftmailer-bundle": "^2.3.10",
    "symfony/symfony": "3.3.*",
    "twig/twig": "^1.0||^2.0"
  },
  "require-dev": {
    "sensio/generator-bundle": "^3.0"
  },
  "scripts": {
    "symfony-scripts": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
    ],
    "post-install-cmd": [
      "@symfony-scripts"
    ],
    "post-update-cmd": [
      "@symfony-scripts"
    ]
  },
  "config": {
    "platform": {
      "php": "7.1"
    },
    "sort-packages": true
  },
  "extra": {
    "symfony-app-dir": "app",
    "symfony-bin-dir": "bin",
    "symfony-var-dir": "var",
    "symfony-web-dir": "web",
    "symfony-assets-install": "relative",
    "incenteev-parameters": {
      "file": "app/config/parameters.yml"
    }
  }
}
```

**Comment by MartinMa** [comment]
**Update**: Issue resolved (for me).

I deleted the project folder and pulled a fresh clone. Now it works.
I also uninstalled and reinstalled xampp and composer (Windows 10 machine). So maybe it had something to do with this as well.

**Comment by fabpot** [comment]
Closing this issue as this bundle is now deprecated. Symfony Flex replaces this bundle.
