### ISSUE TITLE
bootstrap.php.cache generation when running cache:warmup

### ISSUE THREAD

**Issue by renanbr** [sensiolabs/SensioDistributionBundle#325]
I see the https://github.com/sensiolabs/SensioDistributionBundle/issues/100, it's from 2014, so I took the liberty of re-openning this issue

Do you have plans to support `bootstrap.php.cache` generation when running `cache:warmup`?

We're running sf 3.2.9 under docker, and composer with `--no-scripts`

For now i'am running the follow command inside the php container when deploying:

```bash
vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php var vendor --use-new-directory-structure
```

**Comment by fabpot** [comment]
Closing this issue as this bundle is now deprecated. Symfony Flex replaces this bundle.
