### ISSUE TITLE
There is no app/autoload in Symfony 3.3.*

### ISSUE THREAD

**Issue by harpcio** [sensiolabs/SensioDistributionBundle#326]
https://github.com/sensiolabs/SensioDistributionBundle/blob/eb6266b3b472e4002538610b28a0a04bcf94891a/Resources/bin/build_bootstrap.php#L47

[]% ./vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php
PHP Warning:  require_once(/home/deployer/test/releases/20170925134143/app/autoload.php): failed to open stream: No such file or directory in /home/deployer/test/releases/20170925134143/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php on line 56
PHP Fatal error:  require_once(): Failed opening required '/home/deployer/test/releases/20170925134143/app/autoload.php' (include_path='.:/usr/share/php') in /home/deployer/test/releases/20170925134143/vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php on line 56

**Comment by harpcio** [comment]
Solution for Symfony 3.3.*:
 ./vendor/sensio/distribution-bundle/Resources/bin/build_bootstrap.php var vendor

**Comment by Glideh** [comment]
Besides, the [suggestion in the official documentation](http://symfony.com/doc/3.4/configuration/override_dir_structure.html#override-the-vendor-directory) to change the vendor location is not doable.

**Comment by harpcio** [comment]
Vendor location was the same, the app location have been changed to var.
