### ISSUE TITLE
Line Ending should be hardcoded linux and not PHP_EOL

### ISSUE THREAD

**Issue by c33s** [sensiolabs/SensioDistributionBundle#327]
in general symfony is really good in being multiplatform compatible. but the distribution bundle, exaclty the `installRequirementsFile` function, is a weak spot.

there `PHP_EOL` is used for line endings, which means that even if i setup my whole development environment to use linux line endings (using phpstorm, notepad++, gnu tools on windows, cmder, bash, ...) this "feature" of using the system specific line endings breaks it up. each time i do a `composer install` my `symfony_requirements` file is getting touched (all line endings change from linux to windows). if  i would commit it, my git would convert the windows line endings to linux. all i got is a unnecessary commit message.

as far as i know all platforms are able to run php scripts with linux line endings (or whatever line endings). i assume the problem is in the `#!/usr/bin/env php` for directly allowing the execution of the scipt file without `php` before.

is osx able to run such a script file with linux line endings? if yes, it should be changed.
https://confluence.qps.nl/display/KBE/Differences+in+end+of+line+characters+Mac%2C+Windows%2C+and+Linux
```
Windows - Lines end with both a <CR> followed by a <LF> character
Linux  - Lines end with only a <LF> character
Macintosh (Mac OSX) - Lines end with only a <LF> character
Macintosh (old) - Lines end with only a <CR> character
```
looking at the info page about line endings, it looks like switching to `\n` should not be a problem.

 if no we should at least think about adding the `system_requirements` to `.gitignore` in https://github.com/symfony/symfony-standard/, even if i think we should still change the `PHP_EOL` to `\n`

**Comment by fabpot** [comment]
Closing this issue as this bundle is now deprecated. Symfony Flex replaces this bundle.
