### ISSUE TITLE
Config.php shold obey symfony coding standard

### ISSUE THREAD

**Issue by c33s** [sensiolabs/SensioDistributionBundle#328]
currently the file `Resources/skeleton/web/config.php` does not add a semicolon after a method/command so the `php-cs-fixer` has the error `semicolon_after_instruction`

so we should change the skeleton to obey the symfony coding standard by adding the semicolon.

**Comment by osavchenko** [comment]
Check this fir with fixer and it looks good. Probably, can be closed.
