### ISSUE TITLE
I noticed some deprecation notices when running composer install in my symfony3 application.

### ISSUE THREAD

**Issue by VitaNuovaMAX** [sensiolabs/SensioDistributionBundle#329]
Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap declared at C:\xampp\htdocs\Symfony\vendor\sensio\distribution-bundle\Composer\ScriptHandler.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar://C:/xampp/php/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:316

Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache declared at C:\xampp\htdocs\Symfony\vendor\sensio\distribution-bundle\Composer\ScriptHandler.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar://C:/xampp/php/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:316

Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets declared at C:\xampp\htdocs\Symfony\vendor\sensio\distribution-bundle\Composer\ScriptHandler.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar://C:/xampp/php/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:316

Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile declared at C:\xampp\htdocs\Symfony\vendor\sensio\distribution-bundle\Composer\ScriptHandler.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar://C:/xampp/php/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:316

Deprecation Notice: The callback Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget declared at C:\xampp\htdocs\Symfony\vendor\sensio\distribution-bundle\Composer\ScriptHandler.php accepts a Composer\Script\CommandEvent but post-install-cmd events use a Composer\Script\Event instance. Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in phar://C:/xampp/php/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:316

I'm using symfony 3.0.0 and sensio/distribution-bundle 5.0.2
Any help?

**Comment by fabpot** [comment]
You need to upgrade your versions of Symfony and Distribution bundle as they are not supported anymore.

**Comment by stof** [comment]
Latest sensio/distribution-bundle 5.0.x release is 5.0.21, not 5.0.2

**Comment by VitaNuovaMAX** [comment]
Thanks for the help, no more deprecation notices
