### ISSUE TITLE
Some help

### ISSUE THREAD

**Issue by VitaNuovaMAX** [sensiolabs/SensioDistributionBundle#330]
Hello community, could anyone give me a link to download the latest version of Symfony_Standard_Vendors? thanks for your help

**Comment by stof** [comment]
what do you mean by "Symfony_Standard_Vendors" ?

**Comment by VitaNuovaMAX** [comment]
I just need the Symfony project files because I do not have an Internet connection in my home, just here at the University

**Comment by lyrixx** [comment]
In invite you to read: http://symfony.com/download

This issue can be closed

**Comment by VitaNuovaMAX** [comment]
Sorry but I had already reviewed that website and I could not download the file (usually compressed), I could only download Symfony_Standard_Vendors_3.1.0 (in other websites) when v3.3 is already available

**Comment by VitaNuovaMAX** [comment]
For example, here: https://github.com/symfony/symfony-standard shows an updated project to version 3.3.10 but the "vendor" folder does not exist because they use the Internet to download the necessary files.
Now you understand me? I need the files for Symfony3.3.10

**Comment by xabbuh** [comment]
You can use a URL like https://get.symfony.com/Symfony_Standard_Vendors_3.3.10.zip. However, the recommended way is to use the Symfony installer as described on the page @lyrixx gave you (which by the way also just downloads the Standard Edition from that URL and then makes some customisations on top of it).

**Comment by VitaNuovaMAX** [comment]
Thanks you @xabbuh, that was exactly what I needed
