### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by Majkl578** [sensiolabs/SensioDistributionBundle#334]
There seems to be no support for Symfony 4 GA, please allow compatibility with SF4.

**Comment by fabpot** [comment]
There won't be any support for Symfony 4 as Flex is the only supported way.

**Comment by Majkl578** [comment]
Ok, thanks. It should probably be noted somewhere in README though (and maybe explicit conflict would make it more explicit too) as upgrading from 3.x to 4.0 leads to dependency hell due to this package.

**Comment by fabpot** [comment]
Just added a warning in the README:  41c0698 
Indeed, you're right about upgrading from 3.x. Can you create an issue in the symfony/symfony-docs repo about this. It should be added to the upgrade documentation there. /cc @javiereguiluz 
Thanks.

**Comment by Majkl578** [comment]
symfony/symfony-docs#8842

**Comment by pamil** [comment]
What should I do if I need to support both Symfony 3.4 and 4.0 in the same application?

**Comment by xabbuh** [comment]
What do you mean with supporting two Symfony versions in one application?

**Comment by pamil** [comment]
@xabbuh sorry for replying so late. The thing with Sylius is that we want to provide both Symfony 3.4 support (mostly for existing shops) and Symfony 4.0 support (mostly for new shops). 

We're using this bundle for running Composer scripts and the only solution I see to use it with Symfony 4 is to directly use Symfony Flex, but that requires much more effort and double-checking if it does not change too much. We'd like to support Symfony Flex as well, but the first step would be to allow people using Sylius with Symfony 4.0 components (so they actually can use Flex if they want to).

**Comment by umpirsky** [comment]
For many large Symfony applications upgrading to Flex is just not worth it in case you are using `SensioDistributionBundle` just to `buildBootstrap()`.

@pamil Did you find any way to upgrade without much pain other then forking `SensioDistributionBundle`?

**Comment by umpirsky** [comment]
@fabpot If maintaining this bundle is the reason behind dropping support for Symfony 4, we can talk about me volunteering.

**Comment by jvasseur** [comment]
@umpirsky this bundle is deprecated because it's use is really minimal:
 - It adds the `security:check` command to `bin/console` -> you can just use `vendor/bin/security-checker`
 - It gives the requirements checker -> you can use https://github.com/symfony/requirements-checker
 - It gives you script handlers:
   - to build the `bootstrap.php.cache` -> it doesn't give any advantages on PHP7 so you should just stop building it
   - to clear cache and install assets -> you can remplace them with simple calls to the corresponding command in your `composer.json`

**Comment by umpirsky** [comment]
I see, so if project uses PHP7 and uses it only to build `bootstrap.php.cache`, it should just drop it.

Thanks.

**Comment by HeahDude** [comment]
This is true since PHP 5.5 coming bundled with OPCache.

**Comment by teohhanhui** [comment]
To expand on this point:
> to clear cache and install assets -> you can remplace them with simple calls to the corresponding command in your composer.json

You can use something like:

```json
    "scripts": {
        "auto-scripts": [
            "bin/console cache:clear --ansi",
            "bin/console assets:install --symlink --relative --ansi"
        ],
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
```
